export enum ActionTypes {
  EVENTS_FETCH_REQUEST = 'EVENTS_FETCH_REQUEST',
  EVENTS_FETCH_SUCCESS = 'EVENTS_FETCH_SUCCESS',
  EVENTS_FETCH_FALIURE = 'EVENTS_FETCH_FALIURE',

  EVENTS_FETCH_PARAMS_CHANGE = 'EVENTS_FETCH_PARAMS_CHANGE',
}
